### ISSUE TITLE
Increase the ident length in garmin userdata export to 6

### ISSUE THREAD

**Issue by vrlo** [albar965/atools#3]
Garmin user waypoint file `user.wpt` supports waypoint names (idents) 6 alphanumeric characters long ([source](https://fly.garmin.com/fly-garmin/support/gtn-user-waypoint/)). Currently, exporting truncates idents at 5 characters.

**Comment by albar965** [comment]
Thanks a lot. I accidentally merged this to master and had to cherry pick it to branch release/2.0
Alex

**Comment by albar965** [comment]
I can send you a RC for 2.0.3 once finished if you drop me an email.
Alex
